# Generated by Django 4.1 on 2022-09-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomelista', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NomeLista',
        ),
    ]
