# Generated by Django 4.1 on 2022-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('nomelista', '0002_alter_nomelista_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomelista',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='nomelista',
            name='pessoa',
            field=models.ManyToManyField(to='usuario.usuario'),
        ),
    ]
