# Generated by Django 4.1 on 2022-09-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomelista', '0004_remove_nomelista_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NomeLista',
        ),
    ]
