# Generated by Django 4.1 on 2022-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_show', models.CharField(max_length=100)),
                ('descricao_show', models.CharField(max_length=300)),
                ('horario_do_show', models.CharField(max_length=100, null=True)),
                ('data_do_show', models.DateField(null=True)),
            ],
        ),
    ]
