# Generated by Django 4.1 on 2022-09-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=300)),
                ('celular', models.CharField(max_length=300)),
                ('pagamento', models.BooleanField(default=False)),
                ('comprovante', models.ImageField(blank=True, upload_to='static/comprovantes')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_show', models.CharField(max_length=100)),
                ('descricao_show', models.CharField(max_length=300)),
                ('horario_do_show', models.CharField(max_length=100, null=True)),
                ('data_do_show', models.DateField(null=True)),
                ('lista_pix', models.ManyToManyField(to='usuario.usuario')),
                ('lista_reserva_sr', models.ManyToManyField(related_name='show', to='show.nomelista')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='show.show'),
        ),
    ]
