# Generated by Django 4.1 on 2022-08-31 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('show', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='lista_reserva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
