# Generated by Django 4.1 on 2022-09-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_nomelista_pix_show_pix_show_banner_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='pix',
            name='comprovante',
            field=models.ImageField(blank=True, upload_to='static/comprovantes'),
        ),
    ]
