# Generated by Django 4.1 on 2022-08-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomelista', '0004_remove_nomelista_show'),
        ('show', '0003_show_lista_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
    ]
