# Generated by Django 4.1 on 2022-09-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_m2mmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M2MModel',
        ),
    ]
