# Generated by Django 4.1 on 2022-09-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_pix_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomelista',
            name='comprovante',
            field=models.ImageField(blank=True, upload_to='static/comprovantes'),
        ),
        migrations.AddField(
            model_name='nomelista',
            name='pagamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='show',
            name='lista_reserva_sr',
            field=models.ManyToManyField(blank=True, null=True, related_name='show', through='show.Pix', to='show.nomelista'),
        ),
    ]
