# Generated by Django 4.1 on 2022-08-31 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('show', '0004_delete_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_show', models.CharField(max_length=100)),
                ('descricao_show', models.CharField(max_length=300)),
                ('horario_do_show', models.CharField(max_length=100, null=True)),
                ('data_do_show', models.DateField(null=True)),
                ('lista_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
