# Generated by Django 4.1 on 2022-09-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_delete_m2mmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='lista_pix',
        ),
    ]
