# Generated by Django 4.1 on 2022-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('show', '0005_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='lista_reserva',
        ),
        migrations.AddField(
            model_name='show',
            name='lista_reserva',
            field=models.ManyToManyField(to='usuario.usuario'),
        ),
    ]
