# Generated by Django 4.1 on 2022-09-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_shownomelista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowNomelista',
        ),
    ]
