# Generated by Django 4.1 on 2022-09-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_remove_show_lista_reserva_show_lista_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=300)),
                ('celular', models.CharField(max_length=300)),
            ],
        ),
    ]
