# Generated by Django 4.1 on 2022-09-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_nomelista'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='lista_reserva_sr',
            field=models.ManyToManyField(to='show.nomelista'),
        ),
    ]
