# Generated by Django 4.1 on 2022-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_delete_shownomelista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomelista',
            name='nome',
            field=models.CharField(max_length=100, unique='titulo_show'),
        ),
    ]
