# Generated by Django 4.1 on 2022-09-01 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_show_lista_reserva_sr'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='show.show'),
        ),
    ]
