# Generated by Django 4.1 on 2022-09-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0008_alter_nomelista_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomelista',
            name='nome',
            field=models.CharField(error_messages={'unique': 'Este CPF ja foi cadastrado no show.'}, max_length=100, unique='titulo_show'),
        ),
    ]
