# Generated by Django 4.1 on 2022-09-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_alter_nomelista_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomelista',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='show',
            name='titulo_show',
            field=models.CharField(error_messages={'unique': 'Este CPF ja foi cadastrado no show.'}, max_length=100, unique='nome'),
        ),
    ]
