# Generated by Django 4.1 on 2022-09-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0017_alter_nomelista_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomelista',
            name='nome',
            field=models.CharField(max_length=100, unique='lalat'),
        ),
    ]
