# Generated by Django 4.1 on 2022-09-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0018_alter_nomelista_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomelista',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='M2MModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='show.nomelista')),
                ('field2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='show.show')),
            ],
            options={
                'unique_together': {('field1', 'field2')},
            },
        ),
    ]
