# Generated by Django 4.1 on 2022-09-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('show', '0020_delete_m2mmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomelista',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='nomelista',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='nomelista',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='show',
            name='lista_reserva_sr',
        ),
        migrations.AddField(
            model_name='nomelista',
            name='lista_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='show.show'),
        ),
        migrations.AddField(
            model_name='nomelista',
            name='roqueiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='show',
            name='banner',
            field=models.ImageField(blank=True, upload_to='static/banners'),
        ),
        migrations.AddField(
            model_name='show',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
