# Generated by Django 4.1 on 2022-09-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuariosemregistro_usuario_sem_registro'),
        ('show', '0022_alter_nomelista_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomelista',
            name='sem_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuariosemregistro'),
        ),
    ]
