# Generated by Django 4.1 on 2022-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0025_show_quadrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='ticket',
            field=models.ImageField(blank=True, upload_to='static/ticket'),
        ),
        migrations.AddField(
            model_name='show',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
