# Generated by Django 4.1 on 2022-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0026_show_ticket_show_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomelista',
            name='comprovante',
            field=models.ImageField(blank=True, upload_to='comprovantes'),
        ),
    ]
