# Generated by Django 4.1 on 2022-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0027_alter_nomelista_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='descricao_show',
            field=models.TextField(max_length=300),
        ),
    ]
