# Generated by Django 4.1 on 2022-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0028_alter_show_descricao_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='descricao_show',
            field=models.TextField(max_length=2000),
        ),
    ]
