# Generated by Django 4.1 on 2022-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0030_remove_show_carrocel_remove_show_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomelista',
            name='entrou',
            field=models.BooleanField(default=False),
        ),
    ]
