# Generated by Django 4.1 on 2022-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='newsletter_usuario',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(default='novo show', max_length=150),
            preserve_default=False,
        ),
    ]
