# Generated by Django 4.1 on 2022-09-12 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0003_remove_usuario_nome_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSemRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_sem_registro', models.CharField(max_length=11)),
                ('celular_sem_registro', models.CharField(max_length=12)),
                ('usuario_sem_registro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
