# Generated by Django 4.1 on 2022-09-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuariosemregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosemregistro',
            name='usuario_sem_registro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
