# Generated by Django 4.1 on 2022-10-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_usuariosemregistro_email_sem_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permicao_newslleters',
            field=models.BooleanField(default=True),
        ),
    ]
